// ------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion: 14.0.0.0
//  
//     Änderungen an dieser Datei können fehlerhaftes Verhalten verursachen und gehen verloren, wenn
//     der Code neu generiert wird.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SharpDox.Plugins.Chm.Templates.Sites
{
    using System.Linq;
    using System.Text;
    using System.Net;
    using System.Collections.Generic;
    using SharpDox.Model.Repository;
    using SharpDox.Model.Documentation.Token;
    using SharpDox.Plugins.Chm.Steps;
    using SharpDox.Sdk.Config;
    using SharpDox.UML;
    using MarkdownSharp;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public partial class TypeTemplate : TypeTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("\r\n<html>\r\n    <head>\r\n        <title>");
            
            #line 16 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SDType.Name));
            
            #line default
            #line hidden
            this.Write(@"</title>
        <meta content=""text/html; charset=utf-8"" http-equiv=""Content-Type"">
        <link rel=""stylesheet"" type=""text/css"" href=""css/reset.css"">
        <link rel=""stylesheet"" type=""text/css"" href=""css/style.css"">
        <script src=""js/jquery.js"" type=""text/javascript""></script>

        <script type=""text/javascript"">
            var activeDiv;
			var oldHash = window.location.hash;

			$(document).ready(function () {
				onHashChange();
				setHashCheck();
			});

			function onHashChange(){
				if(window.location.hash) {
					if(activeDiv != undefined) activeDiv.hide();
					activeDiv = $(window.location.hash);
					$(window.location.hash).show();
				} else {
					if(activeDiv != undefined) activeDiv.hide();
					activeDiv = $(""#typeIndex"");
					$(""#typeIndex"").show();
				}
			}

			function setHashCheck(){
				oldHash = window.location.hash;

				setInterval(function() {
					if(oldHash !== window.location.hash) {
						oldHash = window.location.hash;
						onHashChange();
					}
				}, 20);
			}
        </script>

    </head>
    <body>
		<div id=""typeIndex"" class=""typesite"">
			<div id=""header"">
				<h2 class=""type-title"">");
            
            #line 59 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SDType.Name));
            
            #line default
            #line hidden
            this.Write("</h2>\r\n\t\t\t\t<span class=\"namespace-title\">");
            
            #line 60 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SDType.Namespace.Fullname));
            
            #line default
            #line hidden
            this.Write("</span>\r\n\t\t\t</div>\r\n\t\t\t<div id=\"subheader\">\r\n\t\t\t\t<a href=\"");
            
            #line 63 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(StepInput.SDProject.ProjectName.Replace(" ", "")));
            
            #line default
            #line hidden
            this.Write("-Index.html\">Start</a> > <a href=\"");
            
            #line 63 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SDType.Namespace.Guid));
            
            #line default
            #line hidden
            this.Write(".html\">");
            
            #line 63 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SDType.Namespace.Fullname));
            
            #line default
            #line hidden
            this.Write("</a> > <a href=\"");
            
            #line 63 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SDType.Guid));
            
            #line default
            #line hidden
            this.Write(".html\">");
            
            #line 63 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SDType.Name));
            
            #line default
            #line hidden
            this.Write("</a>\r\n\t\t\t</div>\r\n\t\t\r\n\t\t\t<div id=\"content\">\r\n\r\n\t\t\t\t<h3 class=\"box-title\">");
            
            #line 68 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(StepInput.DocStrings.Syntax));
            
            #line default
            #line hidden
            this.Write("</h3>\r\n\t\t\t\t<div class=\"syntax-box\">\r\n\t\t\t\t\t");
            
            #line 70 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(WebUtility.HtmlEncode(SDType.Syntax)));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t</div>\r\n\r\n\t\t\t\t");
            
            #line 73 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
 if(SDType.BaseTypes.Count > 0) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t<h3 class=\"box-title\">");
            
            #line 74 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(StepInput.DocStrings.Basetype));
            
            #line default
            #line hidden
            this.Write("</h3>\r\n\t\t\t\t\t<div class=\"list-box\">\r\n\t\t\t\t\t\t<ul>\r\n\t\t\t\t\t\t");
            
            #line 77 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
 foreach(var baseType in SDType.BaseTypes.Select(t => t.Type)) { 
							if(baseType.IsProjectStranger) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t\t<li>");
            
            #line 79 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(baseType.Fullname));
            
            #line default
            #line hidden
            this.Write("</a></li>\r\n\t\t\t\t\t\t\t");
            
            #line 80 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t\t<li><a href=\"");
            
            #line 81 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(baseType.Guid));
            
            #line default
            #line hidden
            this.Write(".html\">");
            
            #line 81 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(baseType.Fullname));
            
            #line default
            #line hidden
            this.Write("</a></li>\r\n\t\t\t\t\t\t\t");
            
            #line 82 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t");
            
            #line 83 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t</ul>\r\n\t\t\t\t\t</div>\r\n\t\t\t\t");
            
            #line 86 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t");
            
            #line 88 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
 if(SDType.ImplementedInterfaces.Count > 0) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t<h3 class=\"box-title\">");
            
            #line 89 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(StepInput.DocStrings.Implements));
            
            #line default
            #line hidden
            this.Write("</h3>\r\n\t\t\t\t\t<div class=\"list-box\">\r\n\t\t\t\t\t\t<ul>\r\n\t\t\t\t\t\t");
            
            #line 92 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
 foreach(var implementedInterface in SDType.ImplementedInterfaces.Select(t => t.Type)) {
							if(implementedInterface.IsProjectStranger) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t\t<li>");
            
            #line 94 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(implementedInterface.Fullname));
            
            #line default
            #line hidden
            this.Write("</a></li>\r\n\t\t\t\t\t\t\t");
            
            #line 95 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t\t<li><a href=\"");
            
            #line 96 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(implementedInterface.Guid));
            
            #line default
            #line hidden
            this.Write(".html\">");
            
            #line 96 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(implementedInterface.Fullname));
            
            #line default
            #line hidden
            this.Write("</a></li>\r\n\t\t\t\t\t\t\t");
            
            #line 97 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t");
            
            #line 98 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t</ul>\r\n\t\t\t\t\t</div>\r\n\t\t\t\t");
            
            #line 101 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t");
            
            #line 103 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
 var documentation = SDType.Documentations.GetElementOrDefault(StepInput.CurrentLanguage);
				if(documentation != null) { 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t\t");
            
            #line 106 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
 if(documentation.Summary.Count > 0) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t<h3 class=\"box-title\">");
            
            #line 107 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(StepInput.DocStrings.Summary));
            
            #line default
            #line hidden
            this.Write("</h3>\r\n\t\t\t\t\t\t<div class=\"doc-box markdown\">\r\n\t\t\t\t\t\t\t");
            
            #line 109 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(new Markdown().Transform(documentation.Summary.ToMarkdown(StepInput.SDProject.Tokens).Transform(Helper.TransformLinkToken))));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t\t\t</div>\r\n\t\t\t\t\t");
            
            #line 111 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t\t");
            
            #line 113 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
 if(documentation.Remarks.Count > 0) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t<h3 class=\"box-title\">");
            
            #line 114 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(StepInput.DocStrings.Remarks));
            
            #line default
            #line hidden
            this.Write("</h3>\r\n\t\t\t\t\t\t<div class=\"doc-box markdown\">\r\n\t\t\t\t\t\t\t");
            
            #line 116 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(new Markdown().Transform(documentation.Remarks.ToMarkdown(StepInput.SDProject.Tokens).Transform(Helper.TransformLinkToken))));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t\t\t</div>\r\n\t\t\t\t\t");
            
            #line 118 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t\t");
            
            #line 120 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
 if(documentation.Example.Count > 0) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t<h3 class=\"box-title\">");
            
            #line 121 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(StepInput.DocStrings.Example));
            
            #line default
            #line hidden
            this.Write("</h3>\r\n\t\t\t\t\t\t<div class=\"doc-box markdown\">\r\n\t\t\t\t\t\t\t");
            
            #line 123 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(new Markdown().Transform(documentation.Example.ToMarkdown(StepInput.SDProject.Tokens).Transform(Helper.TransformLinkToken))));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t\t\t</div>\r\n\t\t\t\t\t");
            
            #line 125 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t\t");
            
            #line 127 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
 if(documentation.Returns.ContainsKey("default")) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t<h3 class=\"box-title\">");
            
            #line 128 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(StepInput.DocStrings.Returns));
            
            #line default
            #line hidden
            this.Write("</h3>\r\n\t\t\t\t\t\t<div class=\"doc-box markdown\">\r\n\t\t\t\t\t\t\t");
            
            #line 130 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(new Markdown().Transform(documentation.Returns["default"].ToMarkdown(StepInput.SDProject.Tokens).Transform(Helper.TransformLinkToken))));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t\t\t</div>\r\n\t\t\t\t\t");
            
            #line 132 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t\t");
            
            #line 134 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
 if(documentation.Exceptions.Count > 0) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t<h3 class=\"box-title\">");
            
            #line 135 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(StepInput.DocStrings.Exceptions));
            
            #line default
            #line hidden
            this.Write("</h3>\r\n\t\t\t\t\t\t<div class=\"doc-box markdown\">\r\n\t\t\t\t\t\t\t");
            
            #line 137 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
 foreach(var exception in documentation.Exceptions) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t\t<p>");
            
            #line 138 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(exception.Key));
            
            #line default
            #line hidden
            this.Write("</p>\r\n\t\t\t\t\t\t\t\t<div class=\"inline\">\r\n\t\t\t\t\t\t\t\t\t");
            
            #line 140 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(new Markdown().Transform(exception.Value.ToMarkdown(StepInput.SDProject.Tokens).Transform(Helper.TransformLinkToken))));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t");
            
            #line 142 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t</div>\r\n\t\t\t\t\t");
            
            #line 144 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t\t");
            
            #line 146 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
 if(documentation.Params.Count > 0) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t<h3 class=\"box-title\">");
            
            #line 147 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(StepInput.DocStrings.Parameters));
            
            #line default
            #line hidden
            this.Write("</h3>\r\n\t\t\t\t\t\t<div class=\"doc-box markdown\">\r\n\t\t\t\t\t\t\t");
            
            #line 149 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
 foreach(var parameter in documentation.Params) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t\t<p>");
            
            #line 150 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Key));
            
            #line default
            #line hidden
            this.Write("</p>\r\n\t\t\t\t\t\t\t\t<div class=\"inline\">\r\n\t\t\t\t\t\t\t\t\t");
            
            #line 152 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(new Markdown().Transform(parameter.Value.ToMarkdown(StepInput.SDProject.Tokens).Transform(Helper.TransformLinkToken))));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t");
            
            #line 154 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t</div>\r\n\t\t\t\t\t");
            
            #line 156 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t\t");
            
            #line 158 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
 if(documentation.TypeParams.Count > 0) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t<h3 class=\"box-title\">");
            
            #line 159 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(StepInput.DocStrings.TypeParameters));
            
            #line default
            #line hidden
            this.Write("</h3>\r\n\t\t\t\t\t\t<div class=\"doc-box markdown\">\r\n\t\t\t\t\t\t\t");
            
            #line 161 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
 foreach(var typeParameter in documentation.TypeParams) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t\t<p>");
            
            #line 162 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(typeParameter.Key));
            
            #line default
            #line hidden
            this.Write("</p>\r\n\t\t\t\t\t\t\t\t<div class=\"inline\">\r\n\t\t\t\t\t\t\t\t\t");
            
            #line 164 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(new Markdown().Transform(typeParameter.Value.ToMarkdown(StepInput.SDProject.Tokens).Transform(Helper.TransformLinkToken))));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t");
            
            #line 166 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t</div>\r\n\t\t\t\t\t");
            
            #line 168 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t\t");
            
            #line 170 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
 if(documentation.SeeAlsos.Count > 0) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t<h3 class=\"box-title\">");
            
            #line 171 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(StepInput.DocStrings.SeeAlso));
            
            #line default
            #line hidden
            this.Write("</h3>\r\n\t\t\t\t\t\t<div class=\"list-box\">\r\n\t\t\t\t\t\t\t<ul>\r\n\t\t\t\t\t\t\t");
            
            #line 174 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
 foreach(var sdToken in documentation.SeeAlsos) 
							{ 
								var seeAlso = (SDSeeToken)sdToken;
								if(!string.IsNullOrEmpty(seeAlso.DeclaringType))
								{
									var identifier = string.Format("{0}.{1}", seeAlso.DeclaringType, seeAlso.Name);
									var sdMember = SDRepository.GetMemberByIdentifier(identifier);
									if(sdMember != null)
									{
										
            
            #line default
            #line hidden
            this.Write(" <li><a href=\"../type/");
            
            #line 183 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(sdMember.DeclaringType.Type.Guid));
            
            #line default
            #line hidden
            this.Write(".html#");
            
            #line 183 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(sdMember.Guid));
            
            #line default
            #line hidden
            this.Write("\">");
            
            #line 183 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(sdMember.Name));
            
            #line default
            #line hidden
            this.Write("</a></li> ");
            
            #line 183 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"

									}
								}
								else
								{
									var identifier = string.Format("{0}.{1}", seeAlso.Namespace, seeAlso.Name);
									var sdType = SDRepository.GetTypeByIdentifier(identifier);
									if(sdType != null)
									{
										
            
            #line default
            #line hidden
            this.Write(" <li><a href=\"../type/");
            
            #line 192 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(sdType.Guid));
            
            #line default
            #line hidden
            this.Write(".html\">");
            
            #line 192 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(sdType.Fullname));
            
            #line default
            #line hidden
            this.Write("</a></li> ");
            
            #line 192 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"

									}
								} 
							} 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t</ul>\r\n\t\t\t\t\t\t</div>\r\n\t\t\t\t\t");
            
            #line 198 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t");
            
            #line 200 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t");
            
            #line 202 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
 if(SDType.Uses.Count > 0) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t<h3 class=\"box-title\">");
            
            #line 203 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(StepInput.DocStrings.Uses));
            
            #line default
            #line hidden
            this.Write("</h3>\r\n\t\t\t\t\t<div class=\"list-box\">\r\n\t\t\t\t\t\t<ul>\r\n\t\t\t\t\t\t");
            
            #line 206 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
 foreach(var use in SDType.Uses.Select(u => u.Type)) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t<li><a href=\"");
            
            #line 207 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(use.Guid));
            
            #line default
            #line hidden
            this.Write(".html\">");
            
            #line 207 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(use.Name));
            
            #line default
            #line hidden
            this.Write("</a></li>\r\n\t\t\t\t\t\t");
            
            #line 208 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t</ul>\r\n\t\t\t\t\t</div>\r\n\t\t\t\t");
            
            #line 211 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t");
            
            #line 213 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
 if(SDType.UsedBy.Count > 0) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t<h3 class=\"box-title\">");
            
            #line 214 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(StepInput.DocStrings.UsedBy));
            
            #line default
            #line hidden
            this.Write("</h3>\r\n\t\t\t\t\t<div class=\"list-box\">\r\n\t\t\t\t\t\t<ul>\r\n\t\t\t\t\t\t");
            
            #line 217 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
 foreach(var used in SDType.UsedBy.Select(u => u.Type)) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t<li><a href=\"");
            
            #line 218 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(used.Guid));
            
            #line default
            #line hidden
            this.Write(".html\">");
            
            #line 218 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(used.Name));
            
            #line default
            #line hidden
            this.Write("</a></li>\r\n\t\t\t\t\t\t");
            
            #line 219 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t</ul>\r\n\t\t\t\t\t</div>\r\n\t\t\t\t");
            
            #line 222 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t<h2 class=\"box-title\">");
            
            #line 224 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(StepInput.DocStrings.Members));
            
            #line default
            #line hidden
            this.Write("</h2>\r\n\t\t\t\t<div class=\"table-box\">\r\n\t\t\t\t\t<table>\r\n\t\t\t\t\t\t<thead>\r\n\t\t\t\t\t\t\t<tr>\r\n\t\t\t" +
                    "\t\t\t\t\t<td></td>\r\n\t\t\t\t\t\t\t\t<td>");
            
            #line 230 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(StepInput.DocStrings.Name));
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t\t\t\t\t\t\t<td>");
            
            #line 231 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(StepInput.DocStrings.Summary));
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t\t\t\t\t\t</tr>\r\n\t\t\t\t\t\t</thead>\r\n\t\t\t\t\t\t<tbody>\r\n\r\n\t\t\t\t\t\t");
            
            #line 236 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
	foreach(var sdField in SDType.Fields) {
							documentation = sdField.Documentations.GetElementOrDefault(StepInput.CurrentLanguage); 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t\t\t\t<tr>\r\n\t\t\t\t\t\t\t\t<td class=\"iconColumn\">\r\n\t\t\t\t\t\t\t\t\t<img alt=\"Field-Icon\" sr" +
                    "c=\"icons/Field_");
            
            #line 241 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(sdField.Accessibility));
            
            #line default
            #line hidden
            this.Write(".png\">\r\n\t\t\t\t\t\t\t\t</td>\r\n\t\t\t\t\t\t\t\t<td>\r\n\t\t\t\t\t\t\t\t\t<a title=\"");
            
            #line 244 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(sdField.Name));
            
            #line default
            #line hidden
            this.Write("\" href=\"");
            
            #line 244 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SDType.Guid));
            
            #line default
            #line hidden
            this.Write(".html#");
            
            #line 244 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(sdField.Guid));
            
            #line default
            #line hidden
            this.Write("\">");
            
            #line 244 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(sdField.Name));
            
            #line default
            #line hidden
            this.Write("</a>\r\n\t\t\t\t\t\t\t\t</td>\t\r\n\t\t\t\t\t\t\t\t<td class=\"markdown\">\r\n\t\t\t\t\t\t\t\t\t");
            
            #line 247 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
 if(documentation != null && documentation.Summary.Count > 0) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t\t\t\t");
            
            #line 248 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(new Markdown().Transform(documentation.Summary.ToMarkdown(StepInput.SDProject.Tokens).Transform(Helper.TransformLinkToken))));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t\t\t\t\t\t");
            
            #line 249 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t\t</td>\r\n\t\t\t\t\t\t\t</tr>\r\n\t\t\t\t\t\t");
            
            #line 252 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
 }		

							foreach(var sdEvent in SDType.Events) {
							documentation = sdEvent.Documentations.GetElementOrDefault(StepInput.CurrentLanguage); 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t\t\t\t<tr>\r\n\t\t\t\t\t\t\t\t<td class=\"iconColumn\">\r\n\t\t\t\t\t\t\t\t\t<img alt=\"Event-Icon\" sr" +
                    "c=\"icons/Event_");
            
            #line 259 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(sdEvent.Accessibility));
            
            #line default
            #line hidden
            this.Write(".png\">\r\n\t\t\t\t\t\t\t\t</td>\r\n\t\t\t\t\t\t\t\t<td>\r\n\t\t\t\t\t\t\t\t\t<a title=\"");
            
            #line 262 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(sdEvent.Name));
            
            #line default
            #line hidden
            this.Write("\" href=\"");
            
            #line 262 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SDType.Guid));
            
            #line default
            #line hidden
            this.Write(".html#");
            
            #line 262 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(sdEvent.Guid));
            
            #line default
            #line hidden
            this.Write("\">");
            
            #line 262 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(sdEvent.Name));
            
            #line default
            #line hidden
            this.Write("</a>\r\n\t\t\t\t\t\t\t\t</td>\t\r\n\t\t\t\t\t\t\t\t<td class=\"markdown\">\r\n\t\t\t\t\t\t\t\t\t");
            
            #line 265 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
 if(documentation != null && documentation.Summary.Count > 0) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t\t\t\t");
            
            #line 266 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(new Markdown().Transform(documentation.Summary.ToMarkdown(StepInput.SDProject.Tokens).Transform(Helper.TransformLinkToken))));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t\t\t\t\t\t");
            
            #line 267 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t\t</td>\r\n\t\t\t\t\t\t\t</tr>\r\n\t\t\t\t\t\t");
            
            #line 270 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
 }

							foreach(var sdConstructor in SDType.Constructors) {
							documentation = sdConstructor.Documentations.GetElementOrDefault(StepInput.CurrentLanguage); 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t\t\t\t<tr>\r\n\t\t\t\t\t\t\t\t<td class=\"iconColumn\">\r\n\t\t\t\t\t\t\t\t\t<img alt=\"Constructor-Ic" +
                    "on\" src=\"icons/Method_");
            
            #line 277 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(sdConstructor.Accessibility));
            
            #line default
            #line hidden
            this.Write(".png\">\r\n\t\t\t\t\t\t\t\t</td>\r\n\t\t\t\t\t\t\t\t<td>\r\n\t\t\t\t\t\t\t\t\t<a title=\"");
            
            #line 280 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(sdConstructor.Name));
            
            #line default
            #line hidden
            this.Write("\" href=\"");
            
            #line 280 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SDType.Guid));
            
            #line default
            #line hidden
            this.Write(".html#");
            
            #line 280 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(sdConstructor.Guid));
            
            #line default
            #line hidden
            this.Write("\">");
            
            #line 280 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(sdConstructor.Name));
            
            #line default
            #line hidden
            this.Write("</a>\r\n\t\t\t\t\t\t\t\t</td>\t\r\n\t\t\t\t\t\t\t\t<td class=\"markdown\">\r\n\t\t\t\t\t\t\t\t\t");
            
            #line 283 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
 if(documentation != null && documentation.Summary.Count > 0) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t\t\t\t");
            
            #line 284 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(new Markdown().Transform(documentation.Summary.ToMarkdown(StepInput.SDProject.Tokens).Transform(Helper.TransformLinkToken))));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t\t\t\t\t\t");
            
            #line 285 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t\t</td>\r\n\t\t\t\t\t\t\t</tr>\r\n\t\t\t\t\t\t");
            
            #line 288 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
 }

							foreach(var sdMethod in SDType.Methods) {
							documentation = sdMethod.Documentations.GetElementOrDefault(StepInput.CurrentLanguage); 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t\t\t\t<tr>\r\n\t\t\t\t\t\t\t\t<td class=\"iconColumn\">\r\n\t\t\t\t\t\t\t\t\t<img alt=\"Constructor-Ic" +
                    "on\" src=\"icons/Method_");
            
            #line 295 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(sdMethod.Accessibility));
            
            #line default
            #line hidden
            this.Write(".png\">\r\n\t\t\t\t\t\t\t\t</td>\r\n\t\t\t\t\t\t\t\t<td>\r\n\t\t\t\t\t\t\t\t\t<a title=\"");
            
            #line 298 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(sdMethod.Name));
            
            #line default
            #line hidden
            this.Write("\" href=\"");
            
            #line 298 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SDType.Guid));
            
            #line default
            #line hidden
            this.Write(".html#");
            
            #line 298 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(sdMethod.Guid));
            
            #line default
            #line hidden
            this.Write("\">");
            
            #line 298 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(sdMethod.Name));
            
            #line default
            #line hidden
            this.Write("</a>\r\n\t\t\t\t\t\t\t\t</td>\t\r\n\t\t\t\t\t\t\t\t<td class=\"markdown\">\r\n\t\t\t\t\t\t\t\t\t");
            
            #line 301 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
 if(documentation != null && documentation.Summary.Count > 0) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t\t\t\t");
            
            #line 302 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(new Markdown().Transform(documentation.Summary.ToMarkdown(StepInput.SDProject.Tokens).Transform(Helper.TransformLinkToken))));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t\t\t\t\t\t");
            
            #line 303 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t\t</td>\r\n\t\t\t\t\t\t\t</tr>\r\n\t\t\t\t\t\t");
            
            #line 306 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
 }

							foreach(var sdProperty in SDType.Properties) {
							documentation = sdProperty.Documentations.GetElementOrDefault(StepInput.CurrentLanguage); 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t\t\t\t<tr>\r\n\t\t\t\t\t\t\t\t<td class=\"iconColumn\">\r\n\t\t\t\t\t\t\t\t\t<img alt=\"Property-Icon\"" +
                    " src=\"icons/Properties_");
            
            #line 313 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(sdProperty.Accessibility));
            
            #line default
            #line hidden
            this.Write(".png\">\r\n\t\t\t\t\t\t\t\t</td>\r\n\t\t\t\t\t\t\t\t<td>\r\n\t\t\t\t\t\t\t\t\t<a title=\"");
            
            #line 316 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(sdProperty.Name));
            
            #line default
            #line hidden
            this.Write("\" href=\"");
            
            #line 316 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SDType.Guid));
            
            #line default
            #line hidden
            this.Write(".html#");
            
            #line 316 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(sdProperty.Guid));
            
            #line default
            #line hidden
            this.Write("\">");
            
            #line 316 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(sdProperty.Name));
            
            #line default
            #line hidden
            this.Write("</a>\r\n\t\t\t\t\t\t\t\t</td>\t\r\n\t\t\t\t\t\t\t\t<td class=\"markdown\">\r\n\t\t\t\t\t\t\t\t\t");
            
            #line 319 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
 if(documentation != null && documentation.Summary.Count > 0) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t\t\t\t");
            
            #line 320 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(new Markdown().Transform(documentation.Summary.ToMarkdown(StepInput.SDProject.Tokens).Transform(Helper.TransformLinkToken))));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t\t\t\t\t\t");
            
            #line 321 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t\t</td>\r\n\t\t\t\t\t\t\t</tr>\r\n\t\t\t\t\t\t");
            
            #line 324 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t\t\t</tbody>\r\n\t\t\t\t\t</table>\r\n\t\t\t\t</div>\r\n\r\n\t\t\t\t");
            
            #line 330 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
	if(!SDType.IsClassDiagramEmpty()) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t<div class=\"diagram-box\">\r\n\t\t\t\t\t\t<img class=\"diagram-image\" src=\"diagrams/");
            
            #line 332 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SDType.Guid));
            
            #line default
            #line hidden
            this.Write(".png\"/>\r\n\t\t\t\t\t</div>\r\n\t\t\t\t");
            
            #line 334 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\t</div>\r\n\t\t</div>\r\n\r\n\t\t");
            
            #line 338 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
	foreach (var constructor in SDType.Constructors)
			{
				var memberTemplate = new MemberTemplate { SDMember = constructor, SDRepository = SDRepository }; 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t");
            
            #line 341 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(memberTemplate.TransformText()));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t");
            
            #line 342 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
  }
			foreach (var method in SDType.Methods)
			{
				var memberTemplate = new MemberTemplate { SDMember = method, SDRepository = SDRepository }; 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t");
            
            #line 346 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(memberTemplate.TransformText()));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t");
            
            #line 347 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
  }
			foreach (var field in SDType.Fields)
			{
				var memberTemplate = new MemberTemplate { SDMember = field, SDRepository = SDRepository }; 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t");
            
            #line 351 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(memberTemplate.TransformText()));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t");
            
            #line 352 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
  }
			foreach (var property in SDType.Properties)
			{
				var memberTemplate = new MemberTemplate { SDMember = property, SDRepository = SDRepository }; 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t");
            
            #line 356 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(memberTemplate.TransformText()));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t");
            
            #line 357 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
  }
			foreach (var sdEvent in SDType.Events)
			{
				var memberTemplate = new MemberTemplate { SDMember = sdEvent, SDRepository = SDRepository }; 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t");
            
            #line 361 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(memberTemplate.TransformText()));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t");
            
            #line 362 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n    </body>\r\n</html>\r\n\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 367 "D:\Github\SharpDox.Plugins.Chm\src\Templates\Sites\TypeTemplate.tt"

public SDType SDType { get; set; } 
public SDRepository SDRepository { get; set; } 

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public class TypeTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
