// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 14.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SharpDox.Plugins.Chm.Templates.Nav
{
    using System.Net;
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using SharpDox.Plugins.Chm.Steps;
    using SharpDox.Model.Repository;
    using SharpDox.Model.Documentation.Article;
    using SharpDox.Sdk.Config;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\gazic0\Downloads\SharpDox.Plugins.Chm-dev\src\Templates\Nav\HhcTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public partial class HhcTemplate : HhcTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("\n");
            this.Write("\n");
            this.Write("\n");
            this.Write("\n");
            this.Write("\n");
            this.Write("\n");
            this.Write("\n");
            this.Write("\n");
            this.Write("\n");
            this.Write("\n\n<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML//EN\">\n<HTML>\n\t<HEAD>\n\t\t<meta name=\"GEN" +
                    "ERATOR\" content=\"sharpDox\">\n\t</HEAD>\n\t<BODY>\n\t\t<ul>\n\t\t<li> <object type=\"text/si" +
                    "temap\">\n\t\t\t\t\t\t<param name=\"Name\" value=\"");
            
            #line 1 "C:\Users\gazic0\Downloads\SharpDox.Plugins.Chm-dev\src\Templates\Nav\HhcTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(StepInput.SDProject.ProjectName));
            
            #line default
            #line hidden
            this.Write("\">\n\t\t\t\t\t\t<param name=\"Local\" value=\"");
            
            #line 1 "C:\Users\gazic0\Downloads\SharpDox.Plugins.Chm-dev\src\Templates\Nav\HhcTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(StepInput.SDProject.ProjectName.Replace(" ", "")));
            
            #line default
            #line hidden
            this.Write("-Index.html\">\n\t\t\t\t\t</object>\n\n\t\t\t<ul>\n\t\t\t\t");
            
            #line 1 "C:\Users\gazic0\Downloads\SharpDox.Plugins.Chm-dev\src\Templates\Nav\HhcTemplate.tt"
 if(StepInput.SDProject.Articles.Count > 0) {
					var articles = StepInput.SDProject.Articles.ContainsKey(StepInput.CurrentLanguage) ? StepInput.SDProject.Articles[StepInput.CurrentLanguage] : StepInput.SDProject.Articles["default"];
					foreach (var article in articles)
					{ 
            
            #line default
            #line hidden
            this.Write("\n\t\t\t\t\t\t<li> <object type=\"text/sitemap\">\n\t\t\t\t\t\t\t\t\t<param name=\"Name\" value=\"");
            
            #line 1 "C:\Users\gazic0\Downloads\SharpDox.Plugins.Chm-dev\src\Templates\Nav\HhcTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(WebUtility.HtmlEncode(article.Title)));
            
            #line default
            #line hidden
            this.Write("\">\n\t\t\t\t\t\t\t\t\t<param name=\"Local\" value=\"");
            
            #line 1 "C:\Users\gazic0\Downloads\SharpDox.Plugins.Chm-dev\src\Templates\Nav\HhcTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Helper.RemoveIllegalCharacters(article.Title.Replace(" ", "_"))));
            
            #line default
            #line hidden
            this.Write(".html\">\n\t\t\t\t\t\t\t</object>\n\n\t\t\t\t\t\t");
            
            #line 1 "C:\Users\gazic0\Downloads\SharpDox.Plugins.Chm-dev\src\Templates\Nav\HhcTemplate.tt"
 if (article is SDDocPlaceholder)
						{ 
							var sdSolution = StepInput.SDProject.Solutions[((SDDocPlaceholder)article).SolutionFile]; 
							var sdRepository = sdSolution.Repositories.SingleOrDefault(r => r.TargetFx.Identifier == StepInput.CurrentTargetFx.Identifier);
							if(sdRepository != null)
							{ 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t<ul>\n\t\t\t\t\t\t\t\t");
            
            #line 1 "C:\Users\gazic0\Downloads\SharpDox.Plugins.Chm-dev\src\Templates\Nav\HhcTemplate.tt"
 var apiNavTemplate = new ApiNavTemplate { SDRepository = sdRepository }; 
            
            #line default
            #line hidden
            this.Write("\n\t\t\t\t\t\t\t\t");
            
            #line 1 "C:\Users\gazic0\Downloads\SharpDox.Plugins.Chm-dev\src\Templates\Nav\HhcTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(apiNavTemplate.TransformText()));
            
            #line default
            #line hidden
            this.Write("\n\t\t\t\t\t\t\t\t</ul>\n\t\t\t\t\t\t\t</li>\n\t\t\t\t\t\t");
            
            #line 1 "C:\Users\gazic0\Downloads\SharpDox.Plugins.Chm-dev\src\Templates\Nav\HhcTemplate.tt"
  } else { 
            
            #line default
            #line hidden
            this.Write(" </li> ");
            
            #line 1 "C:\Users\gazic0\Downloads\SharpDox.Plugins.Chm-dev\src\Templates\Nav\HhcTemplate.tt"
 }
						}
						else if(article.Children.Count > 0)
						{ 
            
            #line default
            #line hidden
            this.Write("\n\t\t\t\t\t\t\t\t<ul>\n\t\t\t\t\t\t\t\t");
            
            #line 1 "C:\Users\gazic0\Downloads\SharpDox.Plugins.Chm-dev\src\Templates\Nav\HhcTemplate.tt"
 var articleNavTemplate = new ArticleNavTemplate { Articles = article.Children }; 
            
            #line default
            #line hidden
            this.Write("\n\t\t\t\t\t\t\t\t");
            
            #line 1 "C:\Users\gazic0\Downloads\SharpDox.Plugins.Chm-dev\src\Templates\Nav\HhcTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(articleNavTemplate.TransformText()));
            
            #line default
            #line hidden
            this.Write("\n\t\t\t\t\t\t\t\t</ul>\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t");
            
            #line 1 "C:\Users\gazic0\Downloads\SharpDox.Plugins.Chm-dev\src\Templates\Nav\HhcTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\n\n\t\t\t\t\t\t</li>\n\t\t\t\t");
            
            #line 1 "C:\Users\gazic0\Downloads\SharpDox.Plugins.Chm-dev\src\Templates\Nav\HhcTemplate.tt"
	}
				} else {
					var sdSolution = StepInput.SDProject.Solutions.Values.Single();
					var sdRepository = sdSolution.Repositories.SingleOrDefault(r => r.TargetFx.Identifier == StepInput.CurrentTargetFx.Identifier);
					if(sdRepository != null)
					{
						var apiNavTemplate = new ApiNavTemplate { SDRepository = sdRepository }; 
            
            #line default
            #line hidden
            this.Write("\n\t\t\t\t\t\t");
            
            #line 1 "C:\Users\gazic0\Downloads\SharpDox.Plugins.Chm-dev\src\Templates\Nav\HhcTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(apiNavTemplate.TransformText()));
            
            #line default
            #line hidden
            this.Write("\n\t\t\t\t");
            
            #line 1 "C:\Users\gazic0\Downloads\SharpDox.Plugins.Chm-dev\src\Templates\Nav\HhcTemplate.tt"
	}
				} 
            
            #line default
            #line hidden
            this.Write("\n\n\t\t\t</ul>\n\t\t</li>\n\t\t</ul>\n\t</BODY>\n</HTML>");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public class HhcTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
